name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_NAME: 'MESBlastBlockGenerator'
  SOLUTION_NAME: 'MESBlastBlockGenerator.sln'

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    # Restore the application
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}

    # Build the application
    - name: Build application
      run: dotnet build ${{ env.SOLUTION_NAME }} --configuration ${{ matrix.configuration }} --no-restore

  publish-windows:
      name: Publish Windows Artifacts
      needs: build
      runs-on: windows-latest
      strategy:
        matrix:
          configuration: [Release]
          runtime: [win-x64, win-x86]
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish for Windows
      run: |
        dotnet publish ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj `
          --configuration ${{ matrix.configuration }} `
          --runtime ${{ matrix.runtime }} `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          --output ./publish/${{ matrix.runtime }}
          
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-windows-${{ matrix.runtime }}
          path: ./publish/${{ matrix.runtime }}/
          retention-days: 30
